[package]
name = "vbmi-bitpack-decoder"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
bytes = "1.11.1"
criterion = "0.5"
parquet = { version = "57.2.0", default-features = false, features = ["experimental"] }
rand = "0.8.5"

[[bench]]
name = "bench_decode"
harness = false